# Generated by Django 2.2.5 on 2019-10-07 19:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import patchwork.models


class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0036_project_commit_url_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', related_query_name='submission', to='patchwork.SubmissionRelation'),
        ),
    ]
