# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-26 17:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import patchwork.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0036_project_commit_url_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='new_diff',
            field=models.TextField(blank=True, db_column='diff', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='new_pull_url',
            field=models.CharField(blank=True, db_column='pull_url', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='new_archived',
            field=models.BooleanField(db_column='archived', default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='new_commit_ref',
            field=models.CharField(blank=True, db_column='commit_ref', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='new_delegate',
            field=models.ForeignKey(blank=True, db_column='delegate', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, related_name='new_patches',
                                    related_query_name='new_patch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='new_hash',
            field=patchwork.fields.HashField(blank=True, db_column='hash', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='new_state',
            field=models.ForeignKey(db_column='state', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='new_patches', related_query_name='new_patch', to='patchwork.State'),
        ),
    ]
