# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-27 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0037_submission_most_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['new_archived', 'project', 'new_state', 'new_delegate'], name='submission_patch_covering_idx'),
        ),
    ]
