# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-18 10:34
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Q

def sanity_check(apps, schema_editor):
    Patch = apps.get_model("patchwork", "Patch")
    db_alias = schema_editor.connection.alias
    diffs = Q(diff__isnull=False, submission_ptr__new_diff__isnull=True)
    pull_urls = Q(pull_url__isnull=False, submission_ptr__new_pull_url__isnull=True)
    query = Patch.objects.using(db_alias).filter(diffs | pull_urls)
    if query.exists():
        raise Exception("It seems not all data has been migrated! bailing out")

class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0038_add_list_index'),
    ]

    operations = [
        migrations.RunPython(
            sanity_check, migrations.RunPython.noop,
        ),
    ]
