# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-27 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patchwork', '0039_sanity_check'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='submission',
            name='submission_patch_covering_idx',
        ),
        migrations.RemoveIndex(
            model_name='patch',
            name='patch_list_covering_idx',
        ),
        migrations.RemoveField(
            model_name='patch',
            name='diff',
        ),
        migrations.RemoveField(
            model_name='patch',
            name='pull_url',
        ),
        migrations.RemoveField(
            model_name='patch',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='patch',
            name='commit_ref',
        ),
        migrations.RemoveField(
            model_name='patch',
            name='delegate',
        ),
        migrations.RemoveField(
            model_name='patch',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='patch',
            name='state',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='new_diff',
            new_name='diff',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='new_pull_url',
            new_name='pull_url',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='new_archived',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='new_commit_ref',
            new_name='commit_ref',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='new_hash',
            new_name='hash',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='new_delegate',
            new_name='delegate',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='new_state',
            new_name='state',
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['archived', 'project', 'state', 'delegate'], name='submission_patch_covering_idx'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='delegate',
            field=models.ForeignKey(blank=True, db_column='delegate', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, related_name='patches',
                                    related_query_name='patch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.ForeignKey(db_column='state', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='patches', related_query_name='patch', to='patchwork.State'),
        ),
    ]
