# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-17 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0040_drop_patch_most_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.ForeignKey(blank=True, help_text=b'The cover letter that this event was created for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patchwork.Submission'),
        ),
        migrations.AlterField(
            model_name='series',
            name='cover_letter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cl_series', to='patchwork.Submission'),
        ),
        migrations.DeleteModel(
            name='CoverLetter',
        ),
    ]
