# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-26 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0041_drop_coverletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='new_number',
            field=models.PositiveSmallIntegerField(db_column='number', default=None, help_text=b'The number assigned to this patch in the series', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='new_series',
            field=models.ForeignKey(blank=True, db_column='series', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_patches', related_query_name='new_patch', to='patchwork.Series'),
        ),
    ]
