# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-27 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0042_submission_series_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patch',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='patch',
            name='number',
        ),
        migrations.RemoveField(
            model_name='patch',
            name='series',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='new_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='new_series',
            new_name='series',
        ),
        migrations.AlterField(
            model_name='submission',
            name='series',
            field=models.ForeignKey(blank=True, db_column='series', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, related_name='patches',
                                    related_query_name='patch', to='patchwork.Series'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set([('series', 'number'), ('msgid', 'project')]),
        ),
    ]
