# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-18 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0043_drop_patch_series_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patch',
            name='tags',
        ),
        migrations.AddField(
            model_name='submission',
            name='tags',
            field=models.ManyToManyField(through='patchwork.PatchTag', to='patchwork.Tag'),
        ),
        migrations.AlterField(
            model_name='patchtag',
            name='patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patchwork.Submission'),
        ),
    ]
