# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-27 18:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0044_move_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patch',
            name='patch_project',
        ),
    ]
