# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-28 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0046_prepare_drop_patch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patch',
        ),
    ]
